on:
  push:
    paths-ignore:
      - "parts/**"
      - "README.md"
      - "flake.nix"
      - "flake.lock"
      - ".editorconfig"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "parts/**"
      - "README.md"
      - "flake.nix"
      - "flake.lock"
      - ".editorconfig"
      - "LICENSE"
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: smlayouteditor.flatpak
          manifest-path: flatpak/io.github.Tofixrs.sm_layout_editor.json
          cache-key: flatpak-builder-${{ github.sha }}
